name: Flowers
version: ${project.version}
main: net.lordofthecraft.flowers.Flowers
author: SeventhCircle
description: A plugin for generating bones and flowers more easily
website: Https://gitlab.lordofthecraft.net/lotc-dev/coders/FlowersAndBones
api-version: 1.13

permissions:
    flowers.use:
        description: Allows a user to duplicate their flowers
