name: FlowersAndBones
version: ${project.version}
main: net.lordofthecraft.gitlab.seventhcircle.flowersandbones.Core
authors: [SeventhCircle]
description: A plugin for generating bones and flowers more easily
website: Https://gitlab.lordofthecraft.net/lotc-dev/coders/FlowersAndBones

permissions:
    FlowersAndBones.use:
        description: Allows a user to duplicate their flowers
